name: CI

on:
  push: 
    branches: ["main"]

jobs: 
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Run a script
      uses: actions/run-a-script@v1
      run: |
           echo Hello World!
           echo Add other actions
           echo test and deploy project 