name: CI

on:
  push: 
    branches: ["main"]

jobs: 
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Setup python
      uses: actions/setup-python@v4
      with: 
            python-version: 3.9
    - name: Run script
      run:  |
          echo Hello World!
          echo Add other actions
          python ./scripts/hello.py